### PR TITLE
Upgrade UglifyJS to address issues

### PR DESCRIPTION
**Pull request by robbytx**
In particular, this appears to resolve:
 * https://github.com/mishoo/UglifyJS2/issues/179

### CODE REVIEW

**Comment by sirugh** [comment]
Isn't uglifyjs2 the NEWER version of uglifyjs? This is a scary change.

**Comment by tnunamak** [comment]
[Yes](https://github.com/mishoo/UglifyJS#new-uglifyjs2), but it appears that the uglify-js package [is actually now uglifyjs2](https://github.com/mishoo/UglifyJS2#install) (actually, it's version 3 according to their README, if you want to be even more confused).

**Comment by robbytx** [comment]
@sirugh ``npm install`` warns:
```
npm WARN deprecated uglify-js2@2.1.11: You can now install this using uglify-js@2.2.0 node_modules/uglify-js
```

So, uglify-js@2.2.0 (and beyond) actually supercede uglify-js2@2.1.11

**Comment by robbytx** [comment]
Do I need to upgrade package.json in my commit?

**Comment by sirugh** [comment]
@robbytx This is a patch, but we will handle that in the "release".

**Comment by robbytx** [comment]
@KikoRamos has verified this in BV Conversations against supported browsers, and I've verified this in our in-development application.

**Pull request merged**
